Fix extension installation
It turns out that npm: prefixed extensions are installed by
default with the --global flag, so we need to prevent permission
errors such as the one below:

```
Error: sudo command failed (exit code 1): npm error code EACCES
 npm error syscall mkdir
 npm error path /opt/homebrew/lib/node_modules/awto-pi-lot
 npm error errno -13
 npm error Error: EACCES: permission denied, mkdir '/opt/homebrew/lib/node_modules/awto-pi-lot'
 npm error     at async mkdir (node:internal/fs/promises:1501:10)
 npm error     at async /opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:585:20
 npm error     at async Promise.allSettled (index 0)
 npm error     at async #reifyPackages (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:317:11)
 npm error     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:127:5)
 npm error     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:146:5)
 npm error     at async Npm.exec (/opt/homebrew/lib/node_modules/npm/lib/npm.js:193:9)
 npm error     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli/entry.js:67:5) {
 npm error   errno: -13,
 npm error   code: 'EACCES',
 npm error   syscall: 'mkdir',
 npm error   path: '/opt/homebrew/lib/node_modules/awto-pi-lot'
 npm error }
```